s={}
name=input("enter friend name")
value=input("enter language:")
s.update({name:value})
name2=input("enter friend name")
value2=input("enter language:")
s.update({name2:value2})
name3=input("enter friend name")
value3=input("enter language:")
s.update({name3:value3})
name4=input("enter friend name")
value4=input("enter language:")
s.update({name4:value4})
print(s)